//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace asplib.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Main
    {
        public long mainid { get; set; }
        public System.Guid session { get; set; }
        public System.DateTime created { get; set; }
        public System.DateTime changed { get; set; }
        public byte[] main { get; set; }
    }
}
