name: Build and Release Libraries

on:
  workflow_dispatch:

jobs:
  build-core:
    uses: ./.github/workflows/libs-build-core.yml
  build-webforms:
    uses: ./.github/workflows/libs-build-webforms.yml
  release:
    needs: [build-core, build-webforms]
    uses: ./.github/workflows/libs-release.yml
    with:
      version: v0.2.0
    secrets:
      nuget_api_key: ${{ secrets.NUGET_API }}
