name: Build Libraries

on:
 workflow_dispatch:

 workflow_call:

jobs:
  build-core:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore libs.core.sln
    - name: Build .NET Core libraries
      run: dotnet build --no-restore libs.core.sln /p:noSmc=true


  build-framework:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Restore dependencies
      run: nuget restore libs.framework.sln
    - name: Build.NET Framework libraries
      run: msbuild libs.framework.sln /p:Configuration=Release