name: Release Libraries

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/libs-build.yml
  publish:
    needs: build
    uses: ./.github/workflows/libs-publish.yml
    secrets:
      nuget_api_key: ${{ secrets.NUGET_API }}