name: Sandbox

on:
  workflow_dispatch:
  workflow_call:

jobs:
  try:
    runs-on: windows-latest
    steps:
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
    - name: view version
      run: msbuild --version