name: Sandbox

on:
  workflow_dispatch:
  workflow_call:

jobs:
  try:
    runs-on: windows-latest
    steps:
    - name: List files
      shell: pwsh
      run: >
        Get-ChildItem -Path "${{ github.workspace }}"
        | Foreach-Object Process
            {
                echo $_.Name
            }
