name: Sandbox

on:
  workflow_dispatch:
  workflow_call:

jobs:
  try:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Get version.txt
      shell: pwsh
      run: |
        $version = Get-Content ${{ github.workspace }}/nuget-info/version.txt
        echo "version=$version" >> $GITHUB_ENV
    - name: Use version.txt
      run: echo ">${{ env.version }}<"