name: Sandbox

on:
  workflow_dispatch:
  workflow_call:

jobs:
  try:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: ncipollo/release-action@v1
      with:
        commit: _action
        tag: v0.2.0-action
        draft: true
        artifacts: "${{ github.workspace }}/packages/*.nupkg"
        bodyFile: "${{ github.workspace }}/.github/workflows/release.md"
